bash auto-complete: on leetcode golang

diff --git a/bashrc_function b/bashrc_function
--- a/bashrc_function
+++ b/bashrc_function
@@ -177,3 +177,53 @@ function _notifyMe()
         python3.6 /home/c4dev/zhw/emc_zhengh3/python/socket_notify.py "'$cmdline' DONE"
     fi
 }
+
+# ON_PROJECT
+export ON_PROJECT='leetcode golang'
+function _com_on()
+{
+    if [ -n "$ON_PROJECT" ]
+    then
+        local cur=${COMP_WORDS[COMP_CWORD]}
+        COMPREPLY=( $(compgen -W "$ON_PROJECT" -- $cur) )
+    fi
+}
+complete -F _com_on on
+function on() {
+    case "$1" in
+    'leetcode')
+        local _leetcode_path='/home/c4dev/zhw/emc_zhengh3/c++/leetcode'
+        if [ -d "$_leetcode_path" ]; then
+            bash --init-file <(echo 'source $HOME/.bashrc;\
+                cd '"$_leetcode_path"';\
+                export PS1="[on '"$1"']$PS1";\
+                function cbuild() { \
+                    g++ -std=c++1y "$@" Main.cpp;\
+                };\
+                function crun() { \
+                    exefile=/tmp/C_build_$$;\
+                    g++ -std=c++1y -o $exefile Main.cpp;\
+                    [ $? -eq 0 ] && $exefile "$@";\
+                    rc=$?;\
+                    rm $exefile;\
+                };\
+                function leetcodeStart() { \
+                    mkdir $1 || return $?;\
+                    cp leetcode_start $1/$1.cpp || return $?;\
+                    [ -e Main.cpp ] && (rm Main.cpp || return $?);\
+                    ln -s $1/$1.cpp Main.cpp || return $?;\
+                }')
+        fi;;
+    'golang')
+        local _golang_path='/home/c4dev/go/src'
+        if [ -d "$_golang_path" ]; then
+            bash --init-file <(echo 'source $HOME/.bashrc;\
+                cd '"$_golang_path"';\
+                export PS1="[on '"$1"']$PS1";\')
+        else
+            echo "[ERROR] '$_golang_path' not exist."
+        fi;;
+    '*')
+        echo "Unknown option `$1`";;
+    esac
+}
